# Generated by Django 5.1.2 on 2024-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_updated_at_alter_emailsaddress_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="otp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
