# Generated by Django 5.1.2 on 2024-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessiontracker_step_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontracker',
            name='step',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password'), ('code_sent', 'Code Sent'), ('code_verified', 'Code Verified')], default='register', max_length=20),
        ),
    ]
